pipeline:
  name: hashicorp-link-checker
  identifier: hashicorplinkchecker
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: actions-harness-testing
        build: <+input>
  stages:
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: HashiCorp Link Checker
                  identifier: HashiCorp_Link_Checker
                  spec:
                    uses: hashicorp/gh-action-check-broken-links@v1
                    with:
                      baseUrl: "'https://hashicorp.com'"
                      files: "'pages/foo.mdx pages/bar.mdx'"
                      whitelist: |
                        https://google.com/whitelist
                        https://yahoo.com/whitelist
        when:
          pipelineStatus: All
    - stage:
        name: linux-arm64
        identifier: linuxarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: HashiCorp Link Checker
                  identifier: HashiCorp_Link_Checker
                  spec:
                    uses: hashicorp/gh-action-check-broken-links@v1
                    with:
                      baseUrl: "'https://hashicorp.com'"
                      files: "'pages/foo.mdx pages/bar.mdx'"
                      whitelist: |
                        https://google.com/whitelist
                        https://yahoo.com/whitelist
        when:
          pipelineStatus: All
    - stage:
        name: windows-amd64
        identifier: windowsamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: HashiCorp Link Checker
                  identifier: HashiCorp_Link_Checker
                  spec:
                    uses: hashicorp/gh-action-check-broken-links@v1
                    with:
                      baseUrl: "'https://hashicorp.com'"
                      files: "'pages/foo.mdx pages/bar.mdx'"
                      whitelist: |
                        https://google.com/whitelist
                        https://yahoo.com/whitelist
        when:
          pipelineStatus: All
    - stage:
        name: windows-arm64
        identifier: windowsarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: HashiCorp Link Checker
                  identifier: HashiCorp_Link_Checker
                  spec:
                    uses: hashicorp/gh-action-check-broken-links@v1
                    with:
                      baseUrl: "'https://hashicorp.com'"
                      files: "'pages/foo.mdx pages/bar.mdx'"
                      whitelist: |
                        https://google.com/whitelist
                        https://yahoo.com/whitelist
        when:
          pipelineStatus: All
    - stage:
        name: macos-arm64
        identifier: macosarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: HashiCorp Link Checker
                  identifier: HashiCorp_Link_Checker
                  spec:
                    uses: hashicorp/gh-action-check-broken-links@v1
                    with:
                      baseUrl: "'https://hashicorp.com'"
                      files: "'pages/foo.mdx pages/bar.mdx'"
                      whitelist: |
                        https://google.com/whitelist
                        https://yahoo.com/whitelist
        when:
          pipelineStatus: All
