pipeline:
  name: securestacxk-abom-test
  identifier: securestacxkabomtest
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: Flocast-SIH
        build: <+input>
  stages:
    - stage:
        identifier: linuxamd64
        type: CI
        name: linux-amd64
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: Create_ABOM
                  type: Action
                  name: Create ABOM
                  spec:
                    uses: SecureStackCo/actions-abom@v0.1.3
                    with:
                      BH_API_KEY: c574b6f2-5bf8-498f-b843-28815319cbf5.AtHP7PelNdtiacsuAS5D
                      BH_APP_ID: c66e9d29-8a15-46db-93b6-b163e3e261bf
                      BH_SEVERITY: critical
    - stage:
        identifier: linuxarm64
        type: CI
        name: linux-arm64
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: Create_ABOM
                  type: Action
                  name: Create ABOM
                  spec:
                    uses: SecureStackCo/actions-abom@v0.1.3
                    with:
                      SECURESTACK_API_KEY: c574b6f2-5bf8-498f-b843-28815319cbf5.AtHP7PelNdtiacsuAS5D
                      SECURESTACK_APP_ID: c66e9d29-8a15-46db-93b6-b163e3e261bf
                      severity: critical
        when:
          pipelineStatus: All
    - stage:
        identifier: windowsamd64
        type: CI
        name: windows-amd64
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: Create_ABOM
                  type: Action
                  name: Create ABOM
                  spec:
                    uses: SecureStackCo/actions-abom@v0.1.3
                    with:
                      SECURESTACK_API_KEY: c574b6f2-5bf8-498f-b843-28815319cbf5.AtHP7PelNdtiacsuAS5D
                      SECURESTACK_APP_ID: c66e9d29-8a15-46db-93b6-b163e3e261bf
                      severity: critical
        when:
          pipelineStatus: All
    - stage:
        identifier: windowsarm64
        type: CI
        name: windows-arm64
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: Create_ABOM
                  type: Action
                  name: Create ABOM
                  spec:
                    uses: SecureStackCo/actions-abom@v0.1.3
                    with:
                      SECURESTACK_API_KEY: c574b6f2-5bf8-498f-b843-28815319cbf5.AtHP7PelNdtiacsuAS5D
                      SECURESTACK_APP_ID: c66e9d29-8a15-46db-93b6-b163e3e261bf
                      severity: critical
        when:
          pipelineStatus: All
    - stage:
        identifier: macarm64
        type: CI
        name: mac-arm64
        description: ""
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: Create_ABOM
                  type: Action
                  name: Create ABOM
                  spec:
                    uses: SecureStackCo/actions-abom@v0.1.3
                    with:
                      SECURESTACK_API_KEY: c574b6f2-5bf8-498f-b843-28815319cbf5.AtHP7PelNdtiacsuAS5D
                      SECURESTACK_APP_ID: c66e9d29-8a15-46db-93b6-b163e3e261bf
                      severity: critical
        when:
          pipelineStatus: All
