pipeline:
  name: test-ml
  identifier: testml
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: actions-harness-testing
        build: <+input>
  stages:
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: MegaLinter
                  identifier: MegaLinter
                  spec:
                    uses: oxsecurity/megalinter@v7.1.0
                    env:
                      VALIDATE_ALL_CODEBASE: "true"
                      GITHUB_TOKEN: <+secrets.getValue("junepat")>
                      APPLY_FIXES: all
                      APPLY_FIXES_EVENT: pull_request
                      APPLY_FIXES_MODE: commit
                  when:
                    stageStatus: All
        when:
          pipelineStatus: All
    - stage:
        name: linux-arm64
        identifier: linuxarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: MegaLinter
                  identifier: MegaLinter
                  spec:
                    uses: oxsecurity/megalinter@v7.1.0
                    env:
                      VALIDATE_ALL_CODEBASE: "true"
                      GITHUB_TOKEN: <+secrets.getValue("junepat")>
                      APPLY_FIXES: all
                      APPLY_FIXES_EVENT: pull_request
                      APPLY_FIXES_MODE: commit
                  when:
                    stageStatus: All
                  failureStrategies: []
        when:
          pipelineStatus: All
    - stage:
        name: windows-amd64
        identifier: windowsamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: MegaLinter
                  identifier: MegaLinter
                  spec:
                    uses: oxsecurity/megalinter@v7.1.0
                    env:
                      VALIDATE_ALL_CODEBASE: "true"
                      GITHUB_TOKEN: <+secrets.getValue("junepat")>
                      APPLY_FIXES: all
                      APPLY_FIXES_EVENT: pull_request
                      APPLY_FIXES_MODE: commit
                  when:
                    stageStatus: All
                  failureStrategies: []
        when:
          pipelineStatus: All
    - stage:
        name: windows-arm64
        identifier: windowsarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: MegaLinter
                  identifier: MegaLinter
                  spec:
                    uses: oxsecurity/megalinter@v7.1.0
                    env:
                      VALIDATE_ALL_CODEBASE: "true"
                      GITHUB_TOKEN: <+secrets.getValue("junepat")>
                      APPLY_FIXES: all
                      APPLY_FIXES_EVENT: pull_request
                      APPLY_FIXES_MODE: commit
                  when:
                    stageStatus: All
                  failureStrategies: []
        when:
          pipelineStatus: All
    - stage:
        name: macos-arm64
        identifier: macosarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: MegaLinter
                  identifier: MegaLinter
                  spec:
                    uses: oxsecurity/megalinter@v7.1.0
                    env:
                      VALIDATE_ALL_CODEBASE: "true"
                      GITHUB_TOKEN: <+secrets.getValue("junepat")>
                      APPLY_FIXES: all
                      APPLY_FIXES_EVENT: pull_request
                      APPLY_FIXES_MODE: commit
                  when:
                    stageStatus: All
                  failureStrategies: []
        when:
          pipelineStatus: All
