pipeline:
  name: test-bitrise-detekt
  identifier: testbitrisedetekt
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: actions-harness-testing
        build: <+input>
  stages:
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Bitrise
                  name: bitrise android build
                  identifier: bitrise_android_build
                  spec:
                    uses: github.com/bitrise-steplib/bitrise-step-android-lint.git
                    with:
                      MY_STEPLIB_REPO_FORK_GIT_URL: https://github.com/bitrise-samples/android-testing.git
