pipeline:
  name: test-bitrise-detekt
  identifier: testbitrisedetekt
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: actions-harness-testing
        build: <+input>
  stages:
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Bitrise
                  name: Bitrise Detekt
                  identifier: Bitrise_Detekt
                  spec:
                    uses: https://github.com/bitrise-io/bitrise-steplib.git
                    env:
                      BITRISE_STEP_ID: android-detekt
                      BITRISE_STEP_VERSION: "\"0.0.3\""
                      BITRISE_STEP_GIT_CLONE_URL: https://github.com/dzinek/bitrise-step-android-detekt.git
                      TEST_REPO_GIT_CLONE_URL: https://github.com/dzinek/android-testing.git
                      PROJECT_PATH: unit/BasicSample-kotlinAppDetektGradle4.9/
