version: 1
name: testingv1
stages:
  - name: stage
    type: ci
    spec:
      steps:
        - name: APKO
          spec:
            with:
              test: dhw
            image: overtrue/phplint@6.0.0
          type: plugin
        - name: Script
          spec:
            run: echo
          type: script
