pipeline:
  name: tets-phplint
  identifier: tetsphplint
  projectIdentifier: NgLabs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitconnectordhruba
        repoName: actions-harness-testing
        build: <+input>
  stages:
    - stage:
        name: macos-arm64
        identifier: macosarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Check PHP syntax errors
                  identifier: Check_PHP_syntax_errors
                  spec:
                    uses: overtrue/phplint@6.0.0
        when:
          pipelineStatus: All
    - stage:
        name: linux-amd64
        identifier: linuxamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Check PHP syntax errors
                  identifier: Check_PHP_syntax_errors
                  spec:
                    uses: overtrue/phplint@6.0.0
        when:
          pipelineStatus: All
    - stage:
        name: linux-arm64
        identifier: linuxarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Check PHP syntax errors
                  identifier: Check_PHP_syntax_errors
                  spec:
                    uses: overtrue/phplint@6.0.0
        when:
          pipelineStatus: All
    - stage:
        name: windows-amd64
        identifier: windowsamd64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Check PHP syntax errors
                  identifier: Check_PHP_syntax_errors
                  spec:
                    uses: overtrue/phplint@9.0.4
        when:
          pipelineStatus: All
    - stage:
        name: windows-arm64
        identifier: windowsarm64
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Check PHP syntax errors
                  identifier: Check_PHP_syntax_errors
                  spec:
                    uses: overtrue/phplint@6.0.0
        when:
          pipelineStatus: All
