apiVersion: v1
kind: Pod
metadata:
  name: dummy-workload
  labels:
    app: dummy-app
spec:
  containers:
    - name: dummy-container
      image: nginx:latest
      ports:
        - containerPort: 80
