name: CI
 
on: [push, pull_request]
 
jobs:
  test:
    name: Check Schema
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: GraphQL Inspector Action
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'master:schema.graphql'
